### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by tembun** [Amir0715/YMDB#28]
Как выполнить шаги "0" и "Gentoo" на ОС Windows?

**Comment by Amir0715** [comment]
Эти шаги на Windows нужно пропустить.

**Comment by tembun** [comment]
> Эти шаги на Windows нужно пропустить.

Хорошо. Может, стоит написать об этом в инструкции по установке, чтобы у пользователей Windows не возникало вопросов?
