### ISSUE TITLE
tried executing 'join' but it errored

### ISSUE THREAD

**Issue by UrbanSide** [Amir0715/YMDB#29]
Привет,ловлю такую ошибку после ввода команды !j
`[2023-03-30 10:33:55 +03:00] [42  /Bot-Music   ] [Error] Aralim tried executing 'join' but it errored: System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by Amir0715** [comment]
@UrbanSide, привет! К сожалению я давно не занимаюсь этим проектом, не смогу тебе помочь 😢

**Comment by UrbanSide** [comment]
> @UrbanSide, привет! К сожалению я давно не занимаюсь этим проектом, не смогу тебе помочь 😢

очень жаль,сейчас таких ботов толком нет под яндекс( спасибо
